prompt_text("siemka", "hello and welcome")
print("after prompt text")
color = prompt_choice("siemka", "what is your favorite color?", {"red", "green", "blue"})
print("your favorite color is", color)
name = prompt_text_response("siemka", "what is your name?")
print("your name is", name)
dice = prompt_number_response("siemka", "throw d6")
print("your dice is", dice)
