prompt_text("siemka", "hello and welcome")
log("after prompt text")
color = prompt_choice("siemka", "what is your favorite color?", {"red", "green", "blue"})
log("your favorite color is "..color)
name = prompt_text_response("siemka", "what is your name?")
log("your name is "..name)
dice = prompt_number_response("siemka", "throw d6")
log("your dice is "..tostring(dice))
